// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBL5JbhAl3AUkacx5rSalHPSzmfD_s9jg',
    appId: '1:1002096663780:web:6b6b74b6f4a4d3120ba0f1',
    messagingSenderId: '1002096663780',
    projectId: 'alumni-association-platf0rm',
    authDomain: 'alumni-association-platf0rm.firebaseapp.com',
    storageBucket: 'alumni-association-platf0rm.firebasestorage.app',
    measurementId: 'G-DDMLZP3F1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQsl5wfHF2patr_NccRCbl0AGd-XJ4TI',
    appId: '1:1002096663780:android:4ff85e4c4e52ace40ba0f1',
    messagingSenderId: '1002096663780',
    projectId: 'alumni-association-platf0rm',
    storageBucket: 'alumni-association-platf0rm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdTyx6GAdmSDjle0UVs6iE7_XqsjGpxI',
    appId: '1:1002096663780:ios:2eaa177f6f44b86e0ba0f1',
    messagingSenderId: '1002096663780',
    projectId: 'alumni-association-platf0rm',
    storageBucket: 'alumni-association-platf0rm.firebasestorage.app',
    iosBundleId: 'com.example.newOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdTyx6GAdmSDjle0UVs6iE7_XqsjGpxI',
    appId: '1:1002096663780:ios:2eaa177f6f44b86e0ba0f1',
    messagingSenderId: '1002096663780',
    projectId: 'alumni-association-platf0rm',
    storageBucket: 'alumni-association-platf0rm.firebasestorage.app',
    iosBundleId: 'com.example.newOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBL5JbhAl3AUkacx5rSalHPSzmfD_s9jg',
    appId: '1:1002096663780:web:9aaac32657289c0e0ba0f1',
    messagingSenderId: '1002096663780',
    projectId: 'alumni-association-platf0rm',
    authDomain: 'alumni-association-platf0rm.firebaseapp.com',
    storageBucket: 'alumni-association-platf0rm.firebasestorage.app',
    measurementId: 'G-41RL2DM2NV',
  );
}
